/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: simonthedigger (https://sketchfab.com/abdullahjavedyo90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/covid-19-fbc12f9d1dad4c49a6a1e30de8d5eae5
Title: COVID-19
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CovidModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/covid.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere001_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-80.057, -38.012, 13.957]}
            rotation={[1.296, 0.371, 1.543]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere003_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-33.365, -43.451, -60.34]}
            rotation={[2.88, 1.09, 1.363]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere004_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-62.277, 37.785, 55.821]}
            rotation={[-1.55, 0.393, 2.107]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere006_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-4.148, -49.55, 80.637]}
            rotation={[0.527, 1.455, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere007_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-53.961, -36.04, 63.819]}
            rotation={[0.592, 0.961, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere008_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-64.467, 33.364, -31.003]}
            rotation={[-2.421, 0.71, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[61.968, -35.263, 54.585]}
            rotation={[-2.655, 0.629, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere010_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-3.43, 74.059, 42.796]}
            rotation={[-1.205, 1.561, 1.571]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere011_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-80.274, 27.005, 25.822]}
            rotation={[-1.234, 0.407, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere012_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-3.507, 66.207, -38.576]}
            rotation={[-2.15, 1.521, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere013_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[73.414, -20.257, -23.331]}
            rotation={[-0.462, 0.397, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere014_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[44.01, 11.544, -60.327]}
            rotation={[0.203, 1.019, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere015_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[65.975, 29.326, 44.056]}
            rotation={[-2.966, 0.461, -1.914]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere017_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[69.469, 27.55, -22.14]}
            rotation={[Math.PI / 4, 0.502, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere018_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[10.217, 53.641, 68.77]}
            rotation={[2.442, 1.383, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere019_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[46.1, -53.33, -41.4]}
            rotation={[-1.57, 0.834, -0.906]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere020_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-60.676, -59.69, -19.897]}
            rotation={[1.968, 0.793, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere021_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-38.685, 16.893, -62.812]}
            rotation={[-2.723, 1.144, 1.573]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere022_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-44.16, -2.017, 81.915]}
            rotation={[0.01, 0.954, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere023_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[10.946, -1.36, 91.908]}
            rotation={[-1.671, 1.032, -2.915]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere024_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-3.43, -86.572, 26.487]}
            rotation={[2.969, 1.571, 0]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere026_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[38.455, 49.446, -44.036]}
            rotation={[Math.PI / 4, 1.089, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere027_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-34.179, 26.3, 82.418]}
            rotation={[-0.369, 1.202, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere028_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[-71.375, -17.403, 55.885]}
            rotation={[0.271, 0.7, Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere029_Material005_0.geometry}
            material={materials["Material.005"]}
            position={[13.328, -85.152, -7.282]}
            rotation={[-1.395, 1.398, -Math.PI / 2]}
            scale={207.561}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere031_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-79.387, 5.939, 43.688]}
            rotation={[-2.933, -0.283, 1.7]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere032_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-76.575, -41.819, 30.882]}
            rotation={[-1.207, -0.441, 2.169]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere033_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-86.345, -14.98, 26.475]}
            rotation={[-2.663, -0.148, 1.575]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere034_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-85.459, -9.004, -9.099]}
            rotation={[1.467, 0.004, 1.784]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere035_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-80.982, 20.653, -8.219]}
            rotation={[0.835, -0.42, 1.516]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere036_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-77.307, 6.427, -26.387]}
            rotation={[0.05, -0.471, 1.397]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere037_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-70.195, 30.744, -24.268]}
            rotation={[0.685, -0.619, 1.49]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere038_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-69.887, -4.266, 59.688]}
            rotation={[2.099, -0.372, 0.936]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere039_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-72.164, 41.897, 30.141]}
            rotation={[1.169, -0.479, 1.18]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere040_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-70.859, 44.97, 17.353]}
            rotation={[2.191, -0.535, 1.882]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere041_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-64.289, 49.353, -9.203]}
            rotation={[1.625, -0.67, 1.818]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere042_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-51.157, 44.683, -37.519]}
            rotation={[2.031, -0.294, 2.766]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere044_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-66.11, -32.704, -42.227]}
            rotation={[-0.797, -0.685, 1.335]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere045_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-55.117, -54.823, -38.867]}
            rotation={[-1.169, -0.885, 1.287]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere046_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-65.262, -59.909, -2.069]}
            rotation={[-0.284, -0.347, 2.2]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere047_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-69.309, -55.7, 11.657]}
            rotation={[-1.502, -0.661, 1.646]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere048_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-75.3, -13.108, -33.783]}
            rotation={[-0.78, -1.445, 1.424]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere049_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-39.185, -30.451, -63.966]}
            rotation={[-0.316, -1.168, 1.532]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere050_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-18.905, -47.958, -62.713]}
            rotation={[-0.213, -1.234, 2.326]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere051_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-24.047, 14.854, -70.017]}
            rotation={[1.604, -0.647, 2.789]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere053_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-20.718, 31.534, -65.484]}
            rotation={[-0.652, -1.067, 0.512]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere054_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-12.449, -28.172, -71.095]}
            rotation={[1.261, -0.381, -2.828]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere055_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-6.538, -0.165, -74.556]}
            rotation={[1.62, 0.122, 3.08]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere056_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-58.387, 11.785, -51.641]}
            rotation={[-0.074, -1.469, 1.469]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere057_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-5.253, 29.252, -67.992]}
            rotation={[1.931, -0.17, 2.947]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere058_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[10.211, -2.707, -73.56]}
            rotation={[-1.351, -0.466, 0.114]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere059_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[22.307, -14.864, -70.589]}
            rotation={[-1.961, -0.77, -0.403]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere060_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[18.123, 13.893, -70.731]}
            rotation={[2.607, -1.274, -2.298]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere061_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[36.103, 22.976, -61.331]}
            rotation={[2.646, -1.047, -2.122]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere062_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[22.743, 32.8, -63.385]}
            rotation={[-1.455, -0.823, -0.444]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere063_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[24.635, 61.833, -36.048]}
            rotation={[2.253, -0.479, -2.795]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere064_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[31.112, -38.04, -61.787]}
            rotation={[-2.388, -0.781, -0.576]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere065_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-40.253, 40.148, -50.401]}
            rotation={[1.927, -0.489, 2.553]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere066_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-5.271, 46.087, -59.768]}
            rotation={[2.198, 0.154, 3.048]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere067_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[12.432, 54.192, -52.503]}
            rotation={[2.361, -0.243, -3.007]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere068_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[40.772, 39.073, -51.853]}
            rotation={[2.404, -0.422, -2.6]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere070_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[56.114, -1.674, -53.496]}
            rotation={[-1.902, -0.365, -0.846]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere071_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[15.655, -58.751, -54.558]}
            rotation={[1.193, -0.957, -2.79]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere072_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-29.144, -58.899, -52.167]}
            rotation={[0.411, -0.972, 2.597]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere073_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[65.161, -34.208, -33.552]}
            rotation={[2.544, -0.615, -1.589]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere074_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[69.69, 16.062, -30.327]}
            rotation={[2.915, -0.405, -1.907]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere075_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[69.263, 36.098, -11.77]}
            rotation={[2.683, -0.015, -2.111]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere076_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[72.484, -41.708, -1.771]}
            rotation={[0.739, -0.2, -1.982]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere077_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[79.555, -11.498, -2.165]}
            rotation={[1.974, -0.279, -1.199]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere078_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[74.532, -3.451, -21.917]}
            rotation={[1.245, 0.05, -1.492]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere080_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[78.95, -20.11, 17.889]}
            rotation={[2.009, -0.085, -1.423]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere082_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[71.957, 14.597, 35.975]}
            rotation={[-2.515, 0.463, -1.334]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere083_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[75.029, 28.329, 17.248]}
            rotation={[-1.955, -0.259, -1.823]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere084_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[72.053, 35.617, 13.521]}
            rotation={[-2.03, -0.364, -1.836]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere085_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[67.402, -47.238, 32.189]}
            rotation={[-0.502, -0.001, -2.152]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere086_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[71.54, -10.451, 41.188]}
            rotation={[-0.8, -0.239, -1.674]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere087_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[66.883, 4.734, -39.721]}
            rotation={[-2.943, -0.584, -1.58]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere089_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[52.323, 35.179, 58.928]}
            rotation={[0.325, -0.634, -0.987]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere090_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[49.281, -53.913, 57.641]}
            rotation={[1.681, -0.688, -0.945]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere092_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[61.977, -18.966, 59.59]}
            rotation={[1.933, -0.449, -0.543]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere094_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[62.747, -59.012, 15.034]}
            rotation={[0.367, -0.35, -2.191]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere095_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[60.214, -59.472, -5.67]}
            rotation={[1.369, -0.583, -1.704]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere096_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[27.979, -35.707, 82.355]}
            rotation={[-0.844, -0.762, -2.268]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere097_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[22.904, -26.327, 87.271]}
            rotation={[1.639, -0.53, -0.352]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere098_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[25.946, -3.696, 88.687]}
            rotation={[-1.753, -0.119, -2.852]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere099_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[25.525, 17.839, 84.71]}
            rotation={[0.668, -0.952, -0.685]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere100_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-17.443, -5.553, 92.689]}
            rotation={[1.698, -0.661, 0.134]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere101_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-4.661, 7.981, 92.704]}
            rotation={[-1.704, -0.156, 3.129]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere102_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-6.377, 1.854, 92.895]}
            rotation={[-1.709, -1.369, 3.043]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere103_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-55.487, 10.847, 71.564]}
            rotation={[-2.16, -0.236, 2.599]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere104_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[49.688, -40.306, 67.46]}
            rotation={[1.476, -0.593, -0.899]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere105_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[48.816, -4.333, 75.284]}
            rotation={[1.081, -0.423, -0.835]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere106_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[36.858, 33.053, 70.986]}
            rotation={[-1.801, -0.56, -2.355]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere107_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-27.492, 48.586, 72.212]}
            rotation={[-2.61, -0.968, 2.677]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere108_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-38.009, 62.964, 50.375]}
            rotation={[2.518, -0.235, 2.555]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere109_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-42.069, 49.648, 65.199]}
            rotation={[1.355, -0.826, 0.631]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere110_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-49.927, 41.987, 66.014]}
            rotation={[-2.157, 0.049, 2.562]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere111_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-60.001, 26.154, 66.341]}
            rotation={[-2.85, -0.744, 2.021]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere112_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-46.078, -21.403, 78.335]}
            rotation={[-2.622, -0.963, 1.702]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere113_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-24.511, -54.709, 70.491]}
            rotation={[2.609, -0.747, 0.515]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere114_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-32.874, -76.858, -25.595]}
            rotation={[-0.097, -0.941, 2.521]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere115_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[10.803, -78.184, -31.216]}
            rotation={[0.876, -1.201, -2.724]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere116_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-39.053, -80.631, -0.472]}
            rotation={[0.135, -0.278, 2.771]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere117_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-14.145, -87.683, 8.06]}
            rotation={[-1.556, -1.457, 1.553]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere120_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[45.663, -44.404, -48.883]}
            rotation={[0.205, -0.611, -2.713]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere121_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[42.814, -76.343, 2.287]}
            rotation={[2.827, -0.593, -0.679]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere122_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-22.574, -86.214, 15.066]}
            rotation={[-0.102, -0.156, 2.899]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere124_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[33.052, -80.913, 18.194]}
            rotation={[-0.144, 0.102, -2.766]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere126_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[28.751, -80.802, 29.812]}
            rotation={[0.305, -0.958, -2.534]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere127_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[15.072, -67.674, 63.658]}
            rotation={[0.745, -0.673, -1.157]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere128_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-25.809, -22.316, 88.643]}
            rotation={[-0.529, -0.073, -3.075]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere129_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-16.95, -76.112, 52.321]}
            rotation={[2.74, -0.598, 0.251]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere130_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-1.246, -76.398, 55.897]}
            rotation={[-0.609, -0.134, -2.718]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere131_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[30.439, -60.963, 65.686]}
            rotation={[0.394, -1.15, -1.968]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere133_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-44.625, -47.31, 63.114]}
            rotation={[2.646, -0.61, 0.623]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere134_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-9.339, -36.424, 85.306]}
            rotation={[-0.751, -0.205, -3.065]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere135_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-41.325, -77.579, 24.762]}
            rotation={[-1.172, -0.587, 2.442]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere136_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-51.11, -56.143, 49.788]}
            rotation={[-0.72, 0.023, 2.508]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere137_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-52.887, -69.701, -13.213]}
            rotation={[-2.318, -0.607, 0.8]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere138_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[28.336, 72.571, -12.037]}
            rotation={[-3.096, -0.708, -2.504]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere139_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-28.254, 58.19, -39.593]}
            rotation={[2.561, 0.107, 3.035]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere140_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[9.104, 76.425, -14.162]}
            rotation={[-0.755, -1.324, -0.535]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere141_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-33.767, 69.296, -19.325]}
            rotation={[2.694, -0.117, 2.735]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere142_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[44.941, 66.14, -4.098]}
            rotation={[-3.049, -0.403, -2.55]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere143_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-10.54, 79.638, 6.6]}
            rotation={[3.023, -0.797, 2.992]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere144_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-26.728, 76.3, 1.371]}
            rotation={[2.589, -1.002, 2.594]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere145_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[42.996, 68.254, 12.047]}
            rotation={[-2.384, -0.847, -2.294]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere146_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-11.52, 78.635, 22.26]}
            rotation={[0.68, -1.382, 0.54]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere147_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-44.248, 69.29, 20.216]}
            rotation={[0.43, -0.544, 0.559]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere148_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-14.502, 75.004, 38.232]}
            rotation={[-3.03, -0.99, 2.888]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere150_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-64.157, 51.629, 5.524]}
            rotation={[0.801, -1.158, 1.596]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere151_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[-50.404, 55.979, -24.924]}
            rotation={[1.847, -0.756, 2.192]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere155_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[26.816, 69.162, 42.2]}
            rotation={[-2.312, 0.205, -2.358]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere156_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[32.663, 59.331, 54.155]}
            rotation={[-1.27, -1.135, -1.939]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere157_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[52.526, 59.15, 27.432]}
            rotation={[-2.548, -0.363, -2.411]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere158_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[58.826, 54.696, 3.16]}
            rotation={[-0.439, -0.521, -0.57]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere159_Material003_0.geometry}
            material={materials["Material.003"]}
            position={[51.943, 57.577, -14.699]}
            rotation={[-2.839, -0.64, -2.254]}
            scale={3.074}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_Material001_0.geometry}
            material={materials["Material.001"]}
            position={[-3.43, -4.065, 9.476]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[1.827, 25.931, 97.478]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[7.436, -49.692, 91.024]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-69.816, -65.334, 32.299]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-65.705, -9.256, 77.811]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-69.208, 60.515, 37.561]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-69.453, 51.242, -26.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-75.182, -9.274, -55.091]}
            rotation={[-1.556, -0.289, -0.081]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-89.645, -30.993, -10.821]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[23.304, -78.789, -46.416]}
            rotation={[-1.76, -0.143, -0.355]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-50.825, -67.338, -46.851]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-2.593, 60.199, -62.011]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[66.335, 33.334, -43.98]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[62.631, -25.894, -57.854]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[59.677, -67.264, 47.133]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[67.927, 53.172, -26.946]}
            rotation={[-1.701, 0.168, -0.095]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[59.636, 63.185, 39.408]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[59.841, 14.879, 74.937]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[87.705, 6.771, 16.083]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-4.26, -67.509, 81.802]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[40.896, 57.466, 66.697]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-22.6, 64.066, 73.934]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-80.386, 16.588, 61.868]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-84.239, -32.526, 48.455]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-84.884, 35.222, 42.116]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube036_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-97.879, -1.357, 5.879]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-81.669, -55.304, -2.22]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-86.773, 40.246, 1.286]}
            rotation={[-1.661, 0.251, 0.169]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube040_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-90.056, 7.145, -22.915]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube041_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-77.782, -41.87, -38.608]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube042_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-76.706, 21.515, -40.805]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube043_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-55.613, -28.287, -67.909]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube044_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-49.233, 0.006, -74.196]}
            rotation={[-1.953, -0.094, -0.138]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube046_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-41.235, 38.494, -65.135]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube047_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-22.626, -9.922, -83.127]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube048_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-3.623, -61.914, -67.796]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube049_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-4.706, 10.152, -84.172]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube050_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[14.602, -45.026, -75.286]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube051_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[16.132, 28.036, -78.355]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube054_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[44.363, -10.202, -70.295]}
            rotation={[-1.201, -0.094, 0.026]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube055_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[46.15, 39.906, -61.157]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube056_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[74.872, -7.947, -46.729]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube057_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[72.168, -56.457, -19.768]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube059_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[87.769, 11.099, -12.55]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube060_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[85.139, -39.341, 14.039]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube061_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[78.163, 43.232, 13.702]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube062_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[86.954, -19.464, 31.833]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube064_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[75.461, 0.686, 57.44]}
            rotation={[-1.462, -0.084, -0.172]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube065_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[53.035, -16.857, 83.981]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube067_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[43.032, -49.122, 81.441]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube068_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[41.159, 5.607, 90.639]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[28.245, 33.399, 88.369]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[23.439, -19.819, 100.02]}
            rotation={[-1.606, -0.054, 0.092]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-3.167, -17.009, 102.887]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-18.733, 37.319, 92.589]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-23.794, 0.6, 102.279]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-35.342, -40.441, 87.519]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube077_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-38.388, 81.199, 34.389]}
            rotation={[-2.809, -0.3, 0.041]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube079_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-55.856, 31.482, 80.732]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube080_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-14.684, -84.297, -43.864]}
            rotation={[-1.569, -0.236, 0.015]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube083_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[48.421, -80.036, -19.702]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube084_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-20.97, -93.192, -11.533]}
            rotation={[-1.447, 0.109, 0.128]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube085_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-55.682, -82.875, 14.734]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube086_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[15.023, -96.918, 14.315]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube088_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[60.875, -79.307, 13.935]}
            rotation={[-1.416, -0.587, -0.253]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube089_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-39.159, -82.114, 49.926]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube090_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[31.239, -84.558, 49.189]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube094_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[48.686, 68.181, -28.249]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube095_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-2.973, 81.774, -32.102]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube097_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-33.929, 85.044, -9.13]}
            rotation={[-1.584, -0.026, -0.018]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube098_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[32.295, 84.359, 4.802]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube100_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[15.391, 87.997, 23.265]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube101_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[-55.183, 72.691, -4.283]}
            rotation={[-1.838, 0.008, 0.035]}
            scale={175.429}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube102_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[15.583, 78.76, 62.986]}
            rotation={[-1.417, 0.05, -0.172]}
            scale={175.429}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/covid.glb");
