/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Earth.glb -T 
Files: Earth.glb [760.44KB] > Earth-transformed.glb [153.68KB] (80%)
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-41fc80d85dfd480281f21b74b2de2faa
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function EarthModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/earthCompressed.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Sphere_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2.5, 0.2, 0]}
        scale={1}
      />
    </group>
  );
}

useGLTF.preload("/earthCompressed.glb");
