/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 MountainHome.glb -T 
Files: MountainHome.glb [24.78MB] > MountainHome-transformed.glb [5.93MB] (76%)
Author: solararchitect (https://sketchfab.com/solararchitect)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hero-mountain-83b3fd690ea44e988d086d5165a5f2ca
Title: Hero Mountain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MountainModel(props) {
  const { nodes, materials } = useGLTF('/mountainCompressed.glb')
  const groupRef = useRef();
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mountainCompressed.glb')
