/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: solararchitect (https://sketchfab.com/solararchitect)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hero-mountain-83b3fd690ea44e988d086d5165a5f2ca
Title: Hero Mountain
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MountainModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/mountain.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mountain.glb");
