/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JChing (https://sketchfab.com/JChing0319)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spicy-ramen-noodle-101c08b5c8534944b43959b142a140b1
Title: Spicy Ramen Noodle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RamenModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/ramen.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group
        position={[-0.04, -1.36, 1.3]}
        scale={1.022}
      >
        <group
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.material_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.material_3}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.bowl}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.material}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.meat}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.meat}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.meat}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.soup_mat}
          position={[0.003, 0.039, -0.446]}
          scale={0.01}
          rotation={[-Math.PI / 8, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ramen.glb");
