/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/router-93c561886acc48bab5a34d02f0a463e5
Title: Router
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RouterModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/router.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials["01_-_Default"]}
        rotation={[-Math.PI / 2.5, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/router.glb");
