/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 rubiks.glb -T 
Files: rubiks.glb [369.44KB] > rubiks-transformed.glb [63.94KB] (83%)
Author: tobyporter (https://sketchfab.com/tobyporter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubix-cube-model-19-15659e4d336c454ab0b7f9fc451121fe
Title: Rubix Cube Model 1/9
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RubiksModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/rubiksCompressed.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.pCube82_phong2_0.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.26, 0.042, -0.384]}
        rotation={[0.3, 0.5, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/rubiksCompressed.glb");
