/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tree.glb -T 
Files: tree.glb [9.11MB] > tree-transformed.glb [1.67MB] (82%)
Author: Daniel Gryningstjerna (https://sketchfab.com/dangry)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-for-games-f91d3c3c527d47fdb217c291e4c7df4b
Title: Tree For Games
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TreeModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/treeCompressed.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane197_Material003_0.geometry}
        material={materials["Material.003"]}
        rotation={[-1.385, 0.085, -0.242]}
        scale={1}
      />
      <mesh
        geometry={nodes.Plane197_twig_0.geometry}
        material={materials.twig}
        rotation={[-1.385, 0.085, -0.242]}
        scale={1}
      />
    </group>
  );
}

useGLTF.preload("/treeCompressed.glb");
