/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TimTimGames (https://sketchfab.com/meneer-badger)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/logo-wordpress-52cefc153b1941979b384f5946fa8666
Title: logo wordpress
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WordpressModel(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/wordpress.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.418}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Line068_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
              position={[0.182, 36.382, -1]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/wordpress.glb");
